FIX

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -36,41 +36,66 @@ jobs:
           docker push 50995452/cicd_pipeline_proxy:latest
 
   deploy:
+    runs-on: ubuntu-latest
     needs: build
-    runs-on: [aws-ec2]
 
     steps:
-      # Pull the latest images from DockerHub
-      - name: Pull latest images from Docker Hub
-        run: |
-          docker pull 50995452/cicd_pipeline:latest
-          docker pull 50995452/cicd_pipeline_proxy:latest
+      - name: SSH into Server and Deploy
+        uses: appleboy/ssh-action@v0.1.10
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USER }}
+          key: ${{ secrets.SSH_TOKEN }}
+          script: |
+            set -e  # Stop script on errors
+            
+            cd /home/${{ secrets.SSH_USER }}/TP---PPP  # Adjust the path to your user directory
+            echo "Pulling the latest images..."
+            docker compose pull
+            echo "Restarting the services..."
+            docker compose down
+            docker compose up -d
+            echo "Cleaning up unused Docker images..."
+            docker image prune -af
+            docker compose up -d
 
-      # Stop and remove existing containers
-      - name: Stop and Remove Old Containers
-        run: |
-          docker compose down || true
-          docker rm -f $(docker ps -aq --filter name=cicd_pipeline) || true
-          docker rm -f $(docker ps -aq --filter name=cicd_pipeline_proxy) || true
+#    needs: build
+#    runs-on: [aws-ec2]
+#
+#
+#    steps:
+#      # Pull the latest images from DockerHub
+#      - name: Pull latest images from Docker Hub
+#        run: |
+#          docker pull 50995452/cicd_pipeline:latest
+#          docker pull 50995452/cicd_pipeline_proxy:latest
+#
+#      # Stop and remove existing containers
+#      - name: Stop and Remove Old Containers
+#        run: |
+#          docker compose down || true
+#          docker rm -f $(docker ps -aq --filter name=cicd_pipeline) || true
+#          docker rm -f $(docker ps -aq --filter name=cicd_pipeline_proxy) || true
+#
+#      # Remove old images
+#      - name: Remove old Docker images
+#        run: |
+#          docker rmi -f 50995452/cicd_pipeline:latest || true
+#          docker rmi -f 50995452/cicd_pipeline_proxy:latest || true
+#
+#      # Start new containers using Docker Compose
+#      - name: Start Containers using Docker Compose
+#        run: |
+#
+#          cd /home/${{ secrets.SSH_USER }}/TP---PPP  # Adjust the path to your user directory
+#          echo "Pulling the latest images..."
+#          docker compose pull
+#          echo "Restarting the services..."
+#          docker compose down
+#          docker compose up -d
+#          echo "Cleaning up unused Docker images..."
+#          docker image prune -af
+#          docker compose up -d
 
-      # Remove old images
-      - name: Remove old Docker images
-        run: |
-          docker rmi -f 50995452/cicd_pipeline:latest || true
-          docker rmi -f 50995452/cicd_pipeline_proxy:latest || true
-
-      # Start new containers using Docker Compose
-      - name: Start Containers using Docker Compose
-        run: |
-          
-          cd /home/${{ secrets.SSH_USER }}/TP---PPP  # Adjust the path to your user directory
-          echo "Pulling the latest images..."
-          docker compose pull
-          echo "Restarting the services..."
-          docker compose down
-          docker compose up -d
-          echo "Cleaning up unused Docker images..."
-          docker image prune -af
-          docker compose up -d
           
            
